knockoff-of-rotten-tomatoes/movie_ratings/urls.py
from django.urls import path
from . import views

app_name = "app"
urlpatterns = [
    path('home/', views.home, name='home'),
    path('movies/', views.movie_list, name='movie_list'),
    path('<int:pk>/', views.movie_detail, name='movie_detail'),
    path('<int:pk>/review/new/', views.post_review, name="post_review"),
    path('reviews/', views.review_list, name='review_list'),
    path('reviews/<int:pk>/', views.review_detail, name='review_detail'),
]

knockoff-of-rotten-tomatoes/movie_ratings_project/urls.py
from django.contrib import admin
from django.urls import path, include
from movie_ratings.views import register
from movie_ratings import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home_path'),
    path('movies/', include('movie_ratings.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('register/', register, name='register'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

knockoff-of-rotten-tomatoes/movie_ratings/models.py
from django.db import models
from django.contrib.auth.models import User


class Movie(models.Model):
    title = models.CharField(max_length=255, unique=True)
    image = models.ImageField(upload_to='movie_images/', null=True, blank=True)
    description = models.TextField()
    genre = models.CharField(max_length=100)
    release_year = models.PositiveIntegerField()
    director = models.CharField(max_length=255)
    cast = models.TextField()
    duration = models.PositiveIntegerField()
    language = models.CharField(max_length=50)

    def __str__(self):
        return f"{self.title}"

class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    rating = models.IntegerField(choices=[(i, i) for i in range(1, 6)])
    comment = models.TextField()

    def __str__(self):
        return f"{self.user} - {self.movie}"
    
    class Meta:
        unique_together = (('user', 'movie'),)

knockoff-of-rotten-tomatoes/movie_ratings/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.shortcuts import render, get_object_or_404, redirect
from .models import Movie, Review
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import login
from django.db.models import Avg
from django.db.models import Q



def home(request):
    context = {}
    return render(request, 'movie_ratings/home.html', context)

def movie_list(request):
    search_query = request.GET.get('search')
    movies = Movie.objects.all()
    if search_query:
        movies = movies.filter(Q(title__icontains=search_query))
    context = {}
    if movies.exists():  # Check if any movies are found
        context['movies'] = movies
    else:
        context['no_movies'] = True
    return render(request, 'movie_ratings/movie_list.html', context)    


def movie_detail(request, pk):
    movie = get_object_or_404(Movie, pk=pk)
    reviews = Review.objects.filter(movie=movie)
    average_rating = reviews.aggregate(Avg('rating'))['rating__avg']
    context = {
        'movie': movie,
        'reviews': reviews,
        'average_rating': average_rating
    }
    return render(request, 'movie_ratings/movie_detail.html', context)

@login_required
def review_list(request):
    reviews = Review.objects.all()
    context = {
        'reviews': reviews
    }
    return render(request, 'movie_ratings/review_list.html', context)

@login_required
def post_review(request, pk):
    if request.method == "POST" and request.user.is_authenticated:
        movie = get_object_or_404(Movie, pk=pk)
        
        existing_review = Review.objects.filter(user=request.user, movie=movie).exists()
        if existing_review:
            messages.error(request, "You have already reviewed this movie.")
            return redirect('app:movie_detail', pk=pk)

        review = Review(user=request.user, movie=movie, rating=request.POST['rating'], comment=request.POST['text'])
        review.save()

    return redirect('app:movie_detail', pk=pk)

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('app:home')  # corrected the redirect path
    else:
        form = UserCreationForm()
    return render(request, 'registration/register.html', {'form': form})

@login_required
def review_detail(request, pk):
    review = get_object_or_404(Review, pk=pk)

    if request.method == "POST" and request.user.is_authenticated:
        # Provjeravamo je li trenutni korisnik autor recenzije
        if request.user == review.user:
            # Ako jest, ažuriramo recenziju
            review.rating = request.POST['rating']
            review.comment = request.POST['comment']
            review.save()
            messages.success(request, "Review updated successfully.")
        else:
            messages.error(request, "You are not the author of this review.")
    
    context = {
        'review': review
    }
    
    return render(request, 'movie_ratings/review_detail.html', context)



knockoff-of-rotten-tomatoes/movie_ratings/templates/movie_ratings/base.html
{% load static %}
<html>
<head>
  <title>Knockoff of Rotten Tomatoes</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css"
  integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Oswald:wght@500&display=swap');

  .jumbotron {
    background-image: none;  /* Uklanja pozadinu */
  }

  .rotated-text {
    font-family: 'Oswald', sans-serif;
    color: black;
    transform: rotate(-20deg);  /* Rotira tekst za -20 stupnjeva */
    font-size: 400%;  /* Povećava font za 50% */
  }

  .happy-place {
    position: absolute;
    bottom: 0;
    left: 50%;
    transform: translateX(-50%) translate(5px, 5px);  /* Pomak za 5px jugozapadno */
  }

  .happy-place-bottom-right {
    position: absolute;
    bottom: 0px;
    right: -50px;
    font-family: 'Oswald', sans-serif;
    color: red;
    transform: rotate(-20deg);  /* Rotira tekst za -20 stupnjeva */
    font-size: 120%;  /* Povećava font za 50% */
  }
</style>


  <link rel="stylesheet" href="{% static 'app/css/app.css' %}">
</head>

<body>
  <div class="page-header">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'app:home' %}">Knockoff of Rotten Tomatoes</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'app:home' %}">Home <span class="sr-only">(current)</span></a>
          </li>
        </ul>

        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            {% if request.user.is_authenticated %}
            User: {{ request.user.username }}
            <form action="{% url 'logout' %}" method="post">
              {% csrf_token %}
              <button class="nav-link" type="submit">Logout</button>
            </form>
            {% else %}
            <a class="nav-link" href="{% url 'login' %}">Prijavi se</a>
            </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'register' %}">New User? Register here</a>
            {% endif %}
          </li>
          <li class="nav-item">
            {% if request.user.is_superuser %}
            <a class="nav-link" href="/admin">admin page</a>
            {% endif %}
          </li>
        </ul>
      </div>
    </nav>
  </div>
  <div class="content container">
    <div class="row">
      <div class="col-md-12">
        <div class="jumbotron fluid-jumbotron" style="position: relative; height: 30vh; width: 110%;">
          <div style="position: absolute; top: 0; left: 0;">
              <h1 class="display-4 font-weight-bold rotated-text">Knockoff of</h1>
          </div>
          <div class="happy-place-bottom-right">
              <p class="lead" style="font-size: 150%;">All movies on one place!</p>
          </div>
      </div>
      
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        {% block content %}
        {% endblock %}
      </div>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
    crossorigin="anonymous"></script>
</body>
</html>

knockoff-of-rotten-tomatoes/movie_ratings/templates/movie_ratings/home.html
{% extends 'movie_ratings/base.html' %}
{% block content %}
<h1>Knockoff of Rotten Tomatoes</h1>
<p>Dobrodošli na domaći "Rotten Tomatoes"</p>

<p>
    <a href="{% url 'app:movie_list' %}">Pregledaj filmove</a>
    {% if not request.user.is_authenticated %}
    {% endif %}
</p>
{% endblock content %}

knockoff-of-rotten-tomatoes/movie_ratings/templates/movie_ratings/movie_detail.html
{% extends 'movie_ratings/base.html' %} 
{% block content %}

<div style="text-align: center;">
  <img src="{{ movie.image.url }}" alt="{{ movie.title }}" style="max-width: 600px; max-height: 900px; width: 35%; height: 50%;">
  <h1>{{ movie.title }}</h1>
  <p><strong>Genre:</strong> {{ movie.genre }}</p>
  <p><strong>Director:</strong> {{ movie.director }}</p>
  <p><strong>Release Year:</strong> {{ movie.release_year }}</p>
  <p><strong>Duration:</strong> {{ movie.duration }} minutes</p>
  <p><strong>Language:</strong> {{ movie.language }}</p>
  <p><strong>Cast:</strong> {{ movie.cast }}</p>
  <p><strong>Description:</strong> {{ movie.description }}</p>

  {% if average_rating %}
    <p><strong>Average Rating:</strong> {{ average_rating }}</p>
  {% endif %}

  <div class="col-md-6">
    <h1>Reviews</h1> 
    {% for review in reviews %}
      <p class="review">
        {{ review.user }} - Rating: {{ review.rating }} - {{ review.comment }}
        {% if user.is_authenticated and user == review.user %}
          <a href="{% url 'app:review_detail' pk=review.pk %}">Edit Review</a>
        {% endif %}
      </p>
    {% endfor %}
    
    {% if user.is_authenticated %}
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-danger" role="alert">
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}
      
      <form action="{% url 'app:post_review' movie.id %}" method="post">
        {% csrf_token %}
        <p>
          <label for="review_text">Text</label>
          <input id="review_text" name="text" type="text">
        </p>
        <p>
          <label for="rating">Rating</label>
          <input id="rating" name="rating" type="number" min="1" max="5">
        </p>

        <input type="submit">
      </form>
    {% else %}
      <p>You have to be logged in to post a review.
        <a href="{% url 'login' %}">Prijavi se</a>
      </p>
    {% endif %}
  </div>
</div>

{% endblock %}

knockoff-of-rotten-tomatoes/movie_ratings/templates/movie_ratings/movie_list.html
{% extends 'movie_ratings/base.html' %} 
{% block content %}

<style>
  .movie-container {
    display: flex;
    flex-wrap: wrap;
    justify-content: space-between;
    text-align: center; /* Dodajte ovu liniju kako biste centrirali tekst s slikom */
  }

  .movie-item {
    width: 18%;
    margin-bottom: 20px;
  }

  .movie-item a {
    text-decoration: none;
    color: black;
  }

  .movie-item img {
    display: block;
    margin: 0 auto; /* Ovo će centrirati sliku unutar roditeljskog elementa */
    max-width: 100px;
    max-height: 150px;
  }

  h1 {
    text-align: center; /* Dodajte ovu liniju kako biste centrirali naslov "Movie List" */
  }

</style>

<h1>Movie List</h1>

<form method="GET" action="{% url 'app:movie_list' %}">
  <input type="text" name="search" placeholder="Search movies by name">
  <button type="submit">Search</button>
</form>

{% if no_movies %}
  <p>No movies found. <a href="{% url 'app:movie_list' %}">Show all movies</a></p>
{% else %}
  <div class="movie-container">
    {% for movie in movies %}
    <div class="movie-item">
      <a href="{% url 'app:movie_detail' pk=movie.pk %}">
        <img src="{{ movie.image.url }}" alt="{{ movie.title }}">
        <br>
        {{ movie.title }}
      </a>
    </div>
    {% endfor %}
  </div>
  <p><a href="{% url 'app:movie_list' %}">Show all movies</a></p>
{% endif %}

{% endblock %}

knockoff-of-rotten-tomatoes/movie_ratings/templates/movie_ratings/review_detail.html
<!-- review_detail.html -->

{% extends 'movie_ratings/base.html' %} 
{% block content %}

<h1>{{ review.user }}'s Review</h1>
<p>Rating: {{ review.rating }}</p>
<p>Comment: {{ review.comment }}</p>

{% if user.is_authenticated and user == review.user %}
    <form method="post" action="{% url 'app:review_detail' pk=review.pk %}">
        {% csrf_token %}
        <label for="rating">Edit Rating:</label>
        <input type="number" name="rating" value="{{ review.rating }}" min="1" max="5">
        <br>
        <label for="comment">Edit Comment:</label>
        <input type="text" name="comment" value="{{ review.comment }}">
        <br>
        <input type="submit" value="Save Changes">
    </form>
{% endif %}

<a href="{% url 'app:movie_detail' pk=review.movie.pk %}">Back to Movie Detail</a>

{% endblock %}

knockoff-of-rotten-tomatoes/movie_ratings/templates/movie_ratings/review_list.html
{% extends 'movie_ratings/base.html' %} 
{% block content %}

<h1>Review List</h1>
<ul>
  {% for review in reviews %}
  <li>{{ review.user }} - {{ review.rating }} - {{ review.comment }}</li>
  {% endfor %}
</ul>

{% endblock %}